# Dependabot Configuration

version: 2
updates:
# Enable version updates for npm dependencies
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "03:00"
  open-pull-requests-limit: 10
  rebase-strategy: auto
  versioning-strategy: auto
  allow:
  - dependency-type: "production"
  - dependency-type: "development"
  commit-message:
    prefix: "chore"
    include: "scope"
  ignore:
  # Ignore major updates for critical packages
  - dependency-name: "@nestjs/*"
    update-types: [ "version-update:semver-major" ]

# Enable version updates for GitHub Actions
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "04:00"
  commit-message:
    prefix: "ci"
    include: "scope"

# Enable version updates for Docker images
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "05:00"
