services:
  postgres:
    image: postgres:16-alpine
    container_name: vegan_vita_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vegan_vita_dev
      POSTGRES_INITDB_ARGS: '-c password_encryption=md5'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    command:
      - 'postgres'
      - '-c'
      - 'hba_file=/etc/postgresql/pg_hba.conf'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
