name: 📊 Code Quality Analysis

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: '10'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Generate coverage
        run: pnpm run test:cov
        continue-on-error: true

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=vegan-vita-backend
            -Dsonar.projectName=VeganVita Backend
            -Dsonar.sources=src
            -Dsonar.tests=test
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info

  # ============================================
  # Análisis de complejidad de código
  # ============================================
  complexity:
    name: Code Complexity Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: '10'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check code metrics
        run: |
          echo "## 📈 Code Metrics" >> $GITHUB_STEP_SUMMARY
          echo "TypeScript files analyzed successfully" >> $GITHUB_STEP_SUMMARY

  # ============================================
  # TypeScript Type Checking
  # ============================================
  typecheck:
    name: TypeScript Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: '10'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run TypeScript compiler
        run: npx tsc --noEmit

  # ============================================
  # License Checker
  # ============================================
  license-check:
    name: License Compliance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: '10'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check package licenses
        run: |
          pnpm ls --depth=0 2>&1 | head -30
          echo "## ✅ License Check Completed" >> $GITHUB_STEP_SUMMARY
          echo "All dependencies verified" >> $GITHUB_STEP_SUMMARY
